/*
 * Copyright (C) 2014 The Libphonenumber Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This file is automatically generated by {@link BuildMetadataProtoFromXml}.
 * Please don't modify it directly.
 */

namespace Google.PhoneNumbers {

using System.Collections.Generic;

public class AlternateFormatsCountryCodeSet {
  // A set of all country codes for which data is available.
  internal static ISet<int> getCountryCodeSet() {
    // The capacity is set to %d as there are %d different entries,
    // and this offers a load factor of roughly 0.75.
    ISet<int> countryCodeSet = new HashSet<int>();

    countryCodeSet.Add(971);
    countryCodeSet.Add(43);
    countryCodeSet.Add(61);
    countryCodeSet.Add(359);
    countryCodeSet.Add(55);
    countryCodeSet.Add(506);
    countryCodeSet.Add(49);
    countryCodeSet.Add(372);
    countryCodeSet.Add(34);
    countryCodeSet.Add(358);
    countryCodeSet.Add(679);
    countryCodeSet.Add(44);
    countryCodeSet.Add(995);
    countryCodeSet.Add(350);
    countryCodeSet.Add(30);
    countryCodeSet.Add(385);
    countryCodeSet.Add(36);
    countryCodeSet.Add(62);
    countryCodeSet.Add(972);
    countryCodeSet.Add(81);
    countryCodeSet.Add(855);
    countryCodeSet.Add(94);
    countryCodeSet.Add(352);
    countryCodeSet.Add(373);
    countryCodeSet.Add(95);
    countryCodeSet.Add(505);
    countryCodeSet.Add(31);
    countryCodeSet.Add(675);
    countryCodeSet.Add(63);
    countryCodeSet.Add(351);
    countryCodeSet.Add(595);
    countryCodeSet.Add(381);
    countryCodeSet.Add(7);
    countryCodeSet.Add(66);
    countryCodeSet.Add(90);
    countryCodeSet.Add(255);
    countryCodeSet.Add(380);
    countryCodeSet.Add(58);
    countryCodeSet.Add(84);
    countryCodeSet.Add(27);

    return countryCodeSet;
  }
}
}
