/*
 * Copyright (C) 2014 The Libphonenumber Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* This file is automatically generated by {@link BuildMetadataProtoFromXml}.
 * Please don't modify it directly.
 */

namespace Google.PhoneNumbers {

using System;
using System.Collections.Generic;

public class ShortNumbersRegionCodeSet {
  // A set of all region codes for which data is available.
  internal static ISet<String> getRegionCodeSet() {
    // The capacity is set to %d as there are %d different entries,
    // and this offers a load factor of roughly 0.75.
    ISet<String> regionCodeSet = new HashSet<String>();

    regionCodeSet.Add("AC");
    regionCodeSet.Add("AD");
    regionCodeSet.Add("AE");
    regionCodeSet.Add("AF");
    regionCodeSet.Add("AG");
    regionCodeSet.Add("AI");
    regionCodeSet.Add("AL");
    regionCodeSet.Add("AM");
    regionCodeSet.Add("AO");
    regionCodeSet.Add("AR");
    regionCodeSet.Add("AS");
    regionCodeSet.Add("AT");
    regionCodeSet.Add("AU");
    regionCodeSet.Add("AW");
    regionCodeSet.Add("AX");
    regionCodeSet.Add("AZ");
    regionCodeSet.Add("BA");
    regionCodeSet.Add("BB");
    regionCodeSet.Add("BD");
    regionCodeSet.Add("BE");
    regionCodeSet.Add("BF");
    regionCodeSet.Add("BG");
    regionCodeSet.Add("BH");
    regionCodeSet.Add("BI");
    regionCodeSet.Add("BJ");
    regionCodeSet.Add("BL");
    regionCodeSet.Add("BM");
    regionCodeSet.Add("BN");
    regionCodeSet.Add("BO");
    regionCodeSet.Add("BQ");
    regionCodeSet.Add("BR");
    regionCodeSet.Add("BS");
    regionCodeSet.Add("BT");
    regionCodeSet.Add("BW");
    regionCodeSet.Add("BY");
    regionCodeSet.Add("BZ");
    regionCodeSet.Add("CA");
    regionCodeSet.Add("CC");
    regionCodeSet.Add("CD");
    regionCodeSet.Add("CH");
    regionCodeSet.Add("CI");
    regionCodeSet.Add("CK");
    regionCodeSet.Add("CL");
    regionCodeSet.Add("CM");
    regionCodeSet.Add("CN");
    regionCodeSet.Add("CO");
    regionCodeSet.Add("CR");
    regionCodeSet.Add("CU");
    regionCodeSet.Add("CV");
    regionCodeSet.Add("CW");
    regionCodeSet.Add("CX");
    regionCodeSet.Add("CY");
    regionCodeSet.Add("CZ");
    regionCodeSet.Add("DE");
    regionCodeSet.Add("DJ");
    regionCodeSet.Add("DK");
    regionCodeSet.Add("DM");
    regionCodeSet.Add("DO");
    regionCodeSet.Add("DZ");
    regionCodeSet.Add("EC");
    regionCodeSet.Add("EE");
    regionCodeSet.Add("EG");
    regionCodeSet.Add("EH");
    regionCodeSet.Add("ES");
    regionCodeSet.Add("ET");
    regionCodeSet.Add("FI");
    regionCodeSet.Add("FJ");
    regionCodeSet.Add("FK");
    regionCodeSet.Add("FM");
    regionCodeSet.Add("FO");
    regionCodeSet.Add("FR");
    regionCodeSet.Add("GA");
    regionCodeSet.Add("GB");
    regionCodeSet.Add("GD");
    regionCodeSet.Add("GE");
    regionCodeSet.Add("GF");
    regionCodeSet.Add("GG");
    regionCodeSet.Add("GH");
    regionCodeSet.Add("GI");
    regionCodeSet.Add("GL");
    regionCodeSet.Add("GM");
    regionCodeSet.Add("GN");
    regionCodeSet.Add("GP");
    regionCodeSet.Add("GR");
    regionCodeSet.Add("GT");
    regionCodeSet.Add("GU");
    regionCodeSet.Add("GW");
    regionCodeSet.Add("GY");
    regionCodeSet.Add("HK");
    regionCodeSet.Add("HN");
    regionCodeSet.Add("HR");
    regionCodeSet.Add("HT");
    regionCodeSet.Add("HU");
    regionCodeSet.Add("ID");
    regionCodeSet.Add("IE");
    regionCodeSet.Add("IL");
    regionCodeSet.Add("IM");
    regionCodeSet.Add("IN");
    regionCodeSet.Add("IQ");
    regionCodeSet.Add("IR");
    regionCodeSet.Add("IS");
    regionCodeSet.Add("IT");
    regionCodeSet.Add("JE");
    regionCodeSet.Add("JM");
    regionCodeSet.Add("JO");
    regionCodeSet.Add("JP");
    regionCodeSet.Add("KE");
    regionCodeSet.Add("KG");
    regionCodeSet.Add("KH");
    regionCodeSet.Add("KI");
    regionCodeSet.Add("KM");
    regionCodeSet.Add("KN");
    regionCodeSet.Add("KR");
    regionCodeSet.Add("KW");
    regionCodeSet.Add("KY");
    regionCodeSet.Add("KZ");
    regionCodeSet.Add("LA");
    regionCodeSet.Add("LB");
    regionCodeSet.Add("LC");
    regionCodeSet.Add("LI");
    regionCodeSet.Add("LK");
    regionCodeSet.Add("LR");
    regionCodeSet.Add("LS");
    regionCodeSet.Add("LT");
    regionCodeSet.Add("LU");
    regionCodeSet.Add("LV");
    regionCodeSet.Add("LY");
    regionCodeSet.Add("MA");
    regionCodeSet.Add("MC");
    regionCodeSet.Add("MD");
    regionCodeSet.Add("ME");
    regionCodeSet.Add("MF");
    regionCodeSet.Add("MG");
    regionCodeSet.Add("MH");
    regionCodeSet.Add("MK");
    regionCodeSet.Add("ML");
    regionCodeSet.Add("MM");
    regionCodeSet.Add("MN");
    regionCodeSet.Add("MO");
    regionCodeSet.Add("MP");
    regionCodeSet.Add("MQ");
    regionCodeSet.Add("MR");
    regionCodeSet.Add("MS");
    regionCodeSet.Add("MT");
    regionCodeSet.Add("MU");
    regionCodeSet.Add("MV");
    regionCodeSet.Add("MW");
    regionCodeSet.Add("MX");
    regionCodeSet.Add("MY");
    regionCodeSet.Add("MZ");
    regionCodeSet.Add("NA");
    regionCodeSet.Add("NC");
    regionCodeSet.Add("NF");
    regionCodeSet.Add("NG");
    regionCodeSet.Add("NI");
    regionCodeSet.Add("NL");
    regionCodeSet.Add("NO");
    regionCodeSet.Add("NP");
    regionCodeSet.Add("NR");
    regionCodeSet.Add("NU");
    regionCodeSet.Add("NZ");
    regionCodeSet.Add("OM");
    regionCodeSet.Add("PA");
    regionCodeSet.Add("PE");
    regionCodeSet.Add("PF");
    regionCodeSet.Add("PG");
    regionCodeSet.Add("PH");
    regionCodeSet.Add("PK");
    regionCodeSet.Add("PL");
    regionCodeSet.Add("PM");
    regionCodeSet.Add("PR");
    regionCodeSet.Add("PT");
    regionCodeSet.Add("PW");
    regionCodeSet.Add("PY");
    regionCodeSet.Add("QA");
    regionCodeSet.Add("RE");
    regionCodeSet.Add("RO");
    regionCodeSet.Add("RS");
    regionCodeSet.Add("RU");
    regionCodeSet.Add("RW");
    regionCodeSet.Add("SA");
    regionCodeSet.Add("SB");
    regionCodeSet.Add("SC");
    regionCodeSet.Add("SD");
    regionCodeSet.Add("SE");
    regionCodeSet.Add("SG");
    regionCodeSet.Add("SH");
    regionCodeSet.Add("SI");
    regionCodeSet.Add("SJ");
    regionCodeSet.Add("SK");
    regionCodeSet.Add("SL");
    regionCodeSet.Add("SM");
    regionCodeSet.Add("SN");
    regionCodeSet.Add("SR");
    regionCodeSet.Add("ST");
    regionCodeSet.Add("SV");
    regionCodeSet.Add("SX");
    regionCodeSet.Add("SY");
    regionCodeSet.Add("SZ");
    regionCodeSet.Add("TC");
    regionCodeSet.Add("TD");
    regionCodeSet.Add("TG");
    regionCodeSet.Add("TH");
    regionCodeSet.Add("TJ");
    regionCodeSet.Add("TL");
    regionCodeSet.Add("TM");
    regionCodeSet.Add("TN");
    regionCodeSet.Add("TO");
    regionCodeSet.Add("TR");
    regionCodeSet.Add("TT");
    regionCodeSet.Add("TV");
    regionCodeSet.Add("TW");
    regionCodeSet.Add("TZ");
    regionCodeSet.Add("UA");
    regionCodeSet.Add("UG");
    regionCodeSet.Add("US");
    regionCodeSet.Add("UY");
    regionCodeSet.Add("UZ");
    regionCodeSet.Add("VA");
    regionCodeSet.Add("VC");
    regionCodeSet.Add("VE");
    regionCodeSet.Add("VG");
    regionCodeSet.Add("VI");
    regionCodeSet.Add("VN");
    regionCodeSet.Add("VU");
    regionCodeSet.Add("WF");
    regionCodeSet.Add("WS");
    regionCodeSet.Add("YE");
    regionCodeSet.Add("YT");
    regionCodeSet.Add("ZA");
    regionCodeSet.Add("ZM");
    regionCodeSet.Add("ZW");

    return regionCodeSet;
  }
}
}
